k8s-at-home/awesome-home-kubernetes

- README.md
`context` on discord.
Signed-off-by: Zachery Hostens <zacheryph@gmail.com>
> add zacheryph/k8s-gitops

- README.md
Signed-off-by: anthr76 <hello@anthonyrabbito.com>
> Add anthr76 inra repo.

- README.md
And also the video I made for Azure Community Day some months ago.
> Added ams0/rancher-home

- README.md
Signed-off-by: Michael Fornaro <20387402+xUnholy@users.noreply.github.com>
> add xunholy personal k8s-gitops repo

- README.md
Add [nicholaswilde/home-cluster](https://github.com/nicholaswilde/home-cluster/) to README.
**Benefits**
N/A
N/A
N/A
It's a very small setup since I just started migrating to flux this weekend.
> Add nicholaswilde/home-cluster to README

- README.md
Add https://github.com/rust84/k8s-gitops
> Add rust84 to README

- README.md
Signed-off-by: Nick M <4718+rkage@users.noreply.github.com>
add my personal gitops repository to the list of repo's
> add rkage's gitops repo

- README.md
Adding Atomic Cluster link. A guide to building a homelab with Kubecon talk, shopping list, etc.
**Benefits**
Additional resource.
Maybe people won't like it?
- fixes #
> Add atomic cluster and fix spelling error

- README.md
> fix domain change

- README.md
Finally got this cleaned up enough that I'm willing to share it :rocket: 
**Benefits**
> Add toboshii/home-cluster

- README.md
Fixes typo in my repo name :sob: 
**Benefits**
- fixes #
> fix: typo in repo name

- README.md
Signed-off-by: Ryan Walter <rwalt@pm.me>
New Repo to look at, new Possibilities!
> Added Rwaltr Repo

- README.md
Would like to share my cluster with others.
**Benefits**
- fixes #
> Add cbirkenbeul repo

- README.md
> Add Diaoul's repo

- README.md
Adding my cluster to the repo 🎉
> add charlie-haley/home-cluster

- README.md
just figured I would finally add my repo to this list
> finally making a pr for my repo

- README.md
added my humble repo for your consideration
> add phybros/k3s-cluster

- data.json
I moved heqet into a new repo/org. So update the URL & added my homelab config for it.
**Benefits**
Keeping everything up2date.
None... i guess..
- fixes #none
Heqet is a ArgoCD & helm plugin now :sunglasses:
> Update(data.json): Heqet has been moved

- data.json
> add rogerrum/k8s-gitops

- README.md
- data.json
Adding my repo, Truxnell/home-cluster, to the fray, now its a bit more presentable.
> feat: Add Truxnell/home-cluster repo

- README.md
I no longer use the repository listed in this file.
> Update zbigniewzolnierowicz's repository

- data.json
Add [ShadyF/k8s-homelab](https://github.com/shadyf/k8s-homelab) to list of user repos.
**Benefits**
N/A
N/A
N/A
N/A
> Add shadyf/k8s-homelab to list of user repos

- data.json
Signed-off-by: Nat Allan <19149206+Truxnell@users.noreply.github.com>
Update my links description to reflect move away from sidero & new hardware.
> chore: update Truxnell description

- README.md
- data.json
Adding my personal cluster to the shared directory of home clusters.
https://github.com/nshores/k8s-home-ops
**Benefits**
Another cluster for community reference!
> Adding nshores/k8s-home-ops to home list

- data.json
Updated an entry
**Benefits**
More Flux users!
Less Argo Users
t's important and relevant to your pull request, mention that information here.-->
> fix(Rwaltr): Updated Information
